// Code generated by MockGen. DO NOT EDIT.
// Source: client.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	apm "github.com/skynet2/elastic-apm-mcp/pkg/apm"
)

// MockAPMClient is a mock of APMClient interface.
type MockAPMClient struct {
	ctrl     *gomock.Controller
	recorder *MockAPMClientMockRecorder
}

// MockAPMClientMockRecorder is the mock recorder for MockAPMClient.
type MockAPMClientMockRecorder struct {
	mock *MockAPMClient
}

// NewMockAPMClient creates a new mock instance.
func NewMockAPMClient(ctrl *gomock.Controller) *MockAPMClient {
	mock := &MockAPMClient{ctrl: ctrl}
	mock.recorder = &MockAPMClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAPMClient) EXPECT() *MockAPMClientMockRecorder {
	return m.recorder
}

// Environments mocks base method.
func (m *MockAPMClient) Environments(ctx context.Context, start, end string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Environments", ctx, start, end)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Environments indicates an expected call of Environments.
func (mr *MockAPMClientMockRecorder) Environments(ctx, start, end interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Environments", reflect.TypeOf((*MockAPMClient)(nil).Environments), ctx, start, end)
}

// ErrorGet mocks base method.
func (m *MockAPMClient) ErrorGet(ctx context.Context, p apm.ErrorGetParams) ([]map[string]any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ErrorGet", ctx, p)
	ret0, _ := ret[0].([]map[string]any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ErrorGet indicates an expected call of ErrorGet.
func (mr *MockAPMClientMockRecorder) ErrorGet(ctx, p interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ErrorGet", reflect.TypeOf((*MockAPMClient)(nil).ErrorGet), ctx, p)
}

// ErrorGroups mocks base method.
func (m *MockAPMClient) ErrorGroups(ctx context.Context, p apm.ErrorGroupsParams) (map[string]any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ErrorGroups", ctx, p)
	ret0, _ := ret[0].(map[string]any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ErrorGroups indicates an expected call of ErrorGroups.
func (mr *MockAPMClientMockRecorder) ErrorGroups(ctx, p interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ErrorGroups", reflect.TypeOf((*MockAPMClient)(nil).ErrorGroups), ctx, p)
}

// GetAPMIndices mocks base method.
func (m *MockAPMClient) GetAPMIndices(ctx context.Context) (apm.APMIndices, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAPMIndices", ctx)
	ret0, _ := ret[0].(apm.APMIndices)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAPMIndices indicates an expected call of GetAPMIndices.
func (mr *MockAPMClientMockRecorder) GetAPMIndices(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAPMIndices", reflect.TypeOf((*MockAPMClient)(nil).GetAPMIndices), ctx)
}

// LogsSearch mocks base method.
func (m *MockAPMClient) LogsSearch(ctx context.Context, p apm.LogsParams) ([]map[string]any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LogsSearch", ctx, p)
	ret0, _ := ret[0].([]map[string]any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LogsSearch indicates an expected call of LogsSearch.
func (mr *MockAPMClientMockRecorder) LogsSearch(ctx, p interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LogsSearch", reflect.TypeOf((*MockAPMClient)(nil).LogsSearch), ctx, p)
}

// RawSearch mocks base method.
func (m *MockAPMClient) RawSearch(ctx context.Context, index string, body map[string]any) ([]map[string]any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RawSearch", ctx, index, body)
	ret0, _ := ret[0].([]map[string]any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RawSearch indicates an expected call of RawSearch.
func (mr *MockAPMClientMockRecorder) RawSearch(ctx, index, body interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RawSearch", reflect.TypeOf((*MockAPMClient)(nil).RawSearch), ctx, index, body)
}

// ServiceDependencies mocks base method.
func (m *MockAPMClient) ServiceDependencies(ctx context.Context, p apm.DependenciesParams) ([]apm.ServiceDependency, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ServiceDependencies", ctx, p)
	ret0, _ := ret[0].([]apm.ServiceDependency)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ServiceDependencies indicates an expected call of ServiceDependencies.
func (mr *MockAPMClientMockRecorder) ServiceDependencies(ctx, p interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ServiceDependencies", reflect.TypeOf((*MockAPMClient)(nil).ServiceDependencies), ctx, p)
}

// ServiceList mocks base method.
func (m *MockAPMClient) ServiceList(ctx context.Context, p apm.ServiceListParams) ([]apm.Service, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ServiceList", ctx, p)
	ret0, _ := ret[0].([]apm.Service)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ServiceList indicates an expected call of ServiceList.
func (mr *MockAPMClientMockRecorder) ServiceList(ctx, p interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ServiceList", reflect.TypeOf((*MockAPMClient)(nil).ServiceList), ctx, p)
}

// ServiceMetrics mocks base method.
func (m *MockAPMClient) ServiceMetrics(ctx context.Context, p apm.ServiceMetricsParams) (map[string]any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ServiceMetrics", ctx, p)
	ret0, _ := ret[0].(map[string]any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ServiceMetrics indicates an expected call of ServiceMetrics.
func (mr *MockAPMClientMockRecorder) ServiceMetrics(ctx, p interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ServiceMetrics", reflect.TypeOf((*MockAPMClient)(nil).ServiceMetrics), ctx, p)
}

// TraceGet mocks base method.
func (m *MockAPMClient) TraceGet(ctx context.Context, traceID string, p apm.TraceParams) (apm.Trace, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TraceGet", ctx, traceID, p)
	ret0, _ := ret[0].(apm.Trace)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// TraceGet indicates an expected call of TraceGet.
func (mr *MockAPMClientMockRecorder) TraceGet(ctx, traceID, p interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TraceGet", reflect.TypeOf((*MockAPMClient)(nil).TraceGet), ctx, traceID, p)
}

// TraceSearch mocks base method.
func (m *MockAPMClient) TraceSearch(ctx context.Context, p apm.TraceSearchParams) ([]map[string]any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TraceSearch", ctx, p)
	ret0, _ := ret[0].([]map[string]any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// TraceSearch indicates an expected call of TraceSearch.
func (mr *MockAPMClientMockRecorder) TraceSearch(ctx, p interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TraceSearch", reflect.TypeOf((*MockAPMClient)(nil).TraceSearch), ctx, p)
}

// TransactionGroups mocks base method.
func (m *MockAPMClient) TransactionGroups(ctx context.Context, p apm.TransactionGroupsParams) ([]apm.TransactionGroup, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TransactionGroups", ctx, p)
	ret0, _ := ret[0].([]apm.TransactionGroup)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// TransactionGroups indicates an expected call of TransactionGroups.
func (mr *MockAPMClientMockRecorder) TransactionGroups(ctx, p interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TransactionGroups", reflect.TypeOf((*MockAPMClient)(nil).TransactionGroups), ctx, p)
}

// TransactionSamples mocks base method.
func (m *MockAPMClient) TransactionSamples(ctx context.Context, p apm.TransactionSamplesParams) ([]apm.TraceSample, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TransactionSamples", ctx, p)
	ret0, _ := ret[0].([]apm.TraceSample)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// TransactionSamples indicates an expected call of TransactionSamples.
func (mr *MockAPMClientMockRecorder) TransactionSamples(ctx, p interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TransactionSamples", reflect.TypeOf((*MockAPMClient)(nil).TransactionSamples), ctx, p)
}
